---
abstract: unknown
author:
  - 'David Oswald <davido@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.56
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-Bag
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.004000
resources: {}
version: 1.012
